group1 =
group2 =
group3 =
group4 =
group5 =
group6 =
group7 =
group8 =
group9 = 'Atlas Yash Eliana Felix Diana'
group10 = 'Charlie Andrey Akanksha Max Hugo Al-fatihi'
group11 = 'Ioanna Vanessa Ella Alicja Cristian '
group12 = 'Karolina Rachna Luca Alexia Yuyue Jelle'
