group1 =
group2 =
group3 =
group4 =
group5 = ["Kian", "Gonzalo", "Sahir", "Teun", "Tom"]
group6 = ["Angeline", "Matas", "Raven", "Caleb", "Paulina", "Angelica"]
group7 = ["Mate", "Martyna", "Vincent", "Eryk", "Emma"]
group8 =
group9 =
group10 =
group11 =
group12 =
