group1 =
group2 =
group3 =
group4 =
group5 = ["Kian", "Gonzalo", "Sahir", "Teun", "Tom"]
group6 = ["Angeline", "Matas", "Raven", "Caleb", "Paulina", "Angelica"]
group7 = ["Mate", "Martyna", "Vincent", "Eryk", "Emma"]
group8 = ["Sanne", "Beatris", "Sally", "Alyssa", "Caio", "Hielke"]
group9 = 'Atlas Yash Eliana Felix Diana'
group10 = 'Charlie Andrey Akanksha Max Hugo Al-fatihi'
group11 = 'Ioanna Vanessa Ella Alicja Cristian '
group12 = 'Karolina Rachna Luca Alexia Yuyue Jelle'
